Feat/si 2617 places filter
samir-a-ts/flutter_guide pull request #11
Opened 2023-01-12 13:27 UTC by samir-a-ts

https://user-images.githubusercontent.com/54618146/212078590-6813267b-24d2-4436-ae15-d49ccc5a09bb.mp4

[SI-2617](https://jira.surfstudio.ru/browse/SI-2617)

2023-01-13 13:41 UTC, ekinsdrow requested changes

2023-01-13 13:41 UTC, ekinsdrow commented on lib/api/data/places_list/place.dart
>          return PlaceType.restaurant;
Default добавить с PlaceType.other

2023-01-13 13:41 UTC, ekinsdrow commented on lib/features/places_list/domain/entity/location.dart
> +class Location {
Этот класс не нужен, можно юзать просто Position из geolocator

2023-01-13 13:41 UTC, ekinsdrow commented on lib/features/places_list/domain/repository/geolocation_repository.dart
> +class LocationPermissionNotGrantedException implements Exception {}
Это не особо нужно

2023-01-13 13:41 UTC, ekinsdrow commented on lib/features/places_list/domain/repository/geolocation_repository.dart
> +  Future<Position> requestLocation() async {
Вызов  пермишенов - бизнес логика, нужно это сделать в model

2023-01-13 13:41 UTC, ekinsdrow commented on lib/features/places_list/screens/filter/places_filter_model.dart
> +  Future<void> _requestLocation() async {
Вызов пермишена - здесь

2023-01-13 13:41 UTC, ekinsdrow commented on lib/features/places_list/screens/filter/places_filter_widget.dart
> +extension _PlaceTypeIcons on PlaceType {
Отформатирую, пж

2023-01-13 13:41 UTC, ekinsdrow commented on lib/features/places_list/screens/filter/places_filter_widget.dart
> +class PlacesFilterParameters {
Вынес в отдельный в common

2023-01-13 13:41 UTC, ekinsdrow commented on lib/features/places_list/screens/places_list/places_list_page_model.dart
> +    filteredPlacesListState.content([]);
Убери, сброс фильтров при ривреше

2023-01-13 13:41 UTC, ekinsdrow commented on lib/features/places_list/screens/places_list/places_list_page_model.dart
> +    } on DioError catch (e) {
Надо еще остальные Exception нужно обработать так же

2023-01-13 13:41 UTC, ekinsdrow commented on lib/features/places_list/screens/places_list/places_list_page_model.dart
> +    } on DioError catch (e) {
Тут так же

2023-01-13 13:41 UTC, ekinsdrow commented on test/features/places_list/places/places_list_model_test.dart
> +import 'package:dio/dio.dart';
Тест вернуть в старое состояние

2023-01-13 13:44 UTC, samir-a-ts commented on lib/api/data/places_list/place.dart
>          return PlaceType.restaurant;
в этом switch case не было "other", он возвращается в конце функции, не доглядели

2023-01-13 13:46 UTC, samir-a-ts commented on lib/features/places_list/screens/filter/places_filter_widget.dart
> +class PlacesFilterParameters {
оно только для places_list нужно, вынес в entity

2023-01-13 14:40 UTC, samirakhmedov commented
https://user-images.githubusercontent.com/54618146/212346336-280457e8-1692-46c4-9554-dd0badf5d9b1.mp4

2023-01-16 12:14 UTC, ekinsdrow approved these changes

2023-01-16 12:42 UTC, merged