SI-2582: places list
samir-a-ts/flutter_guide pull request #6
Opened 2022-12-27 17:25 UTC by samir-a-ts

[SI-2582](https://jira.surfstudio.ru/browse/SI-2582)

https://user-images.githubusercontent.com/54618146/209700715-967c0323-1823-4b80-af96-fcc94856676f.mp4

2022-12-28 07:19 UTC, ekinsdrow requested changes
1) Нет PTR (pull to refresh)
2) Очень много лишних комментов
3) Есть проблемки c elementary (Обсудим)

2022-12-28 07:19 UTC, ekinsdrow commented on lib/api/data/places_list/place.dart
> +  /// Initialization.
Зачем комментировать конструктор?

2022-12-28 07:19 UTC, ekinsdrow commented on lib/api/data/places_list/place.dart
> +  final List<String> urls;
Называешь объект urls, при этом в комменте пишешь, что для картинок, не явно

2022-12-28 07:19 UTC, ekinsdrow commented on lib/api/data/places_list/place.dart
> +  /// Name of this place.
Какой смысл вообще в таком комменте и дркгих подобных? "Имя - это имя"?

2022-12-28 07:19 UTC, ekinsdrow commented on lib/api/data/places_list/place.dart
> +  final String placeType;
Enum?

2022-12-28 07:19 UTC, ekinsdrow commented on lib/api/service/places_list/places_list_api.dart
> +  List<PlaceDto> _processRequest(Response<dynamic> response) {
Опять зачем-то маппинг dio ошибок на свою, так еще и не явную? Зачем?

2022-12-28 07:19 UTC, ekinsdrow commented on lib/api/service/places_list/places_list_api.dart
> +  List<PlaceDto> _processRequest(Response<dynamic> response) {
Какая цель у этого метода вообще?

2022-12-28 07:19 UTC, ekinsdrow commented on lib/common/widgets/app_bar.dart
> +  const MainAppBar({
Документация конструктора, что это конструктор?

2022-12-28 07:19 UTC, ekinsdrow commented on lib/features/places_list/di/places_list_scope.dart
> +abstract class IPlacesListScope {
А зачем здесь вообще абстрактный класс? С какой целью?

2022-12-28 07:19 UTC, ekinsdrow commented on lib/features/places_list/domain/mappers/from_dto_to_model.dart
> +  static Place fromDto(PlaceDto dto) => Place(
А зачем? Зачем тебе здесь опять два разных объекта? Чтобы что? Они у тебя по полям не отличаются даже и по логике

2022-12-28 07:19 UTC, ekinsdrow commented on lib/features/places_list/domain/repository/places_list_repository.dart
> +  List<Place> _processRequest(List<PlaceDto> placesObjects) {
Опять непонятный метод

2022-12-28 07:19 UTC, ekinsdrow commented on lib/features/places_list/domain/repository/places_list_repository.dart
> +class PlacesListRepository implements IPlacesListRepository {
На самом деле, здесь излишне делить на репу и дата-сурс, но не страшно

2022-12-28 07:19 UTC, ekinsdrow commented on lib/features/places_list/screens/places_list/widget/places_list_page.dart
> +                    print('test');
Что вот это такое?

2022-12-28 07:19 UTC, ekinsdrow commented on lib/features/places_list/screens/places_list/wm/places_list_widget_model.dart
> +  ListenableState<EntityState<Iterable<Place>>> get placesListState;
Это должно быть в модели

2022-12-28 07:19 UTC, ekinsdrow commented on lib/features/places_list/screens/places_list/wm/places_list_widget_model.dart
> +  ListenableState<bool> get arePlacesLoaded;
И это тоже

2022-12-28 07:19 UTC, ekinsdrow commented on lib/features/places_list/screens/places_list/wm/places_list_widget_model.dart
> +  ListenableState<bool> get arePlacesReloading;
И это? 

PS
Странное, название переменной с are, обычно даже во множественном числе пишут is, чтобы сразу было видно) Но это не критично, просто непривычно) У нас тут не урок грамматики

2022-12-28 07:30 UTC, samir-a-ts commented on lib/api/data/places_list/place.dart
> +  /// Initialization.
В линтере есть правило, типа document_public_apis, поэтому кидает warning, если без комментариев оставлять

2022-12-28 07:30 UTC, samir-a-ts commented on lib/api/data/places_list/place.dart
> +  /// Name of this place.
Опять же, правило линтера

2022-12-28 07:31 UTC, samir-a-ts commented on lib/features/places_list/di/places_list_scope.dart
> +abstract class IPlacesListScope {
В примере делали вот так, вот я и подумал, что нужно так

2022-12-28 07:56 UTC, samir-a-ts commented on lib/common/widgets/app_bar.dart
> +  const MainAppBar({
Опять же, правило линтера

2022-12-28 12:11 UTC, ekinsdrow commented on lib/features/places_list/screens/places_list/wm/places_list_widget_model.dart
> +  ListenableState<EntityState<Iterable<Place>>> get placesListState;
Немного не там, правда написал, геттер в wm может быть, а вот само поле, лучше в модель

2022-12-28 12:11 UTC, ekinsdrow commented on lib/features/places_list/screens/places_list/wm/places_list_widget_model.dart
> +  ListenableState<bool> get arePlacesLoaded;
Тут тоже добавление, что и выше

2022-12-28 15:52 UTC, samir-a-ts commented
https://user-images.githubusercontent.com/54618146/209837866-a32d698a-9092-4241-aef1-b013bbc30636.mp4

2022-12-29 07:35 UTC, ekinsdrow requested changes

2022-12-29 07:35 UTC, ekinsdrow commented on lib/features/places_list/domain/entity/place.dart
> +import 'package:flutter/animation.dart';
Убрать offset и импорт из модельки

2022-12-29 07:35 UTC, ekinsdrow commented on lib/features/places_list/screens/places_list/wm/places_list_widget_model.dart
> +  void dispose() {
Поменять местами dispose контроллера и родителя

2022-12-29 07:35 UTC, ekinsdrow commented on lib/api/data/places_list/place.dart
> +  static PlaceType _fromString(String type) {
А зачем тебе такой switch? Если у тебя названия enum'ов один в один равно строковому значению?

2022-12-29 07:35 UTC, ekinsdrow commented on lib/features/places_list/screens/places_list/model/places_list_page_model.dart
> +  final scroll = ScrollController();
ScrollController это разве бизнес логика? Вчера прямо этот момент обсуждали

2022-12-29 07:35 UTC, ekinsdrow commented on lib/features/places_list/screens/places_list/model/places_list_page_model.dart
> +  void _loadMore() {
Представь, что ты юзал бы bloc

ElementaryModel в данной ситуации можно воспринимать, как блок - сущность, в которую инкапсулируется логика, ты бы это писал тоже в блоке?

2022-12-29 08:56 UTC, samir-a-ts commented on lib/api/data/places_list/place.dart
> +  static PlaceType _fromString(String type) {
а как тогда?

2022-12-29 09:18 UTC, ekinsdrow approved these changes

2022-12-29 09:26 UTC, merged